DROP TABLE "TB_CHATROOM";

CREATE TABLE "TB_CHATROOM" (
	"CHATROOM_NO"	NUMBER		NOT NULL,
	"CHAT_TITLE"	VARCHAR2(4000)		NOT NULL,
	"CHAT_TYPE"	NUMBER		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "TB_CHATROOM"."CHATROOM_NO" IS '채팅방 번호';

COMMENT ON COLUMN "TB_CHATROOM"."CHAT_TITLE" IS '방 제목';

COMMENT ON COLUMN "TB_CHATROOM"."CHAT_TYPE" IS '0 - 1:1 채팅방, 1 - 그룹 채팅방';

COMMENT ON COLUMN "TB_CHATROOM"."CREATE_DATE" IS '채팅방 생성일';

DROP TABLE "TB_CHATCONTENT";

CREATE TABLE "TB_CHATCONTENT" (
	"CHATCONTENT_NO"	NUMBER		NOT NULL,
	"CHATROOM_NO"	NUMBER		NOT NULL,
	"WRITER_NO"	NUMBER		NOT NULL,
	"CHAT_CONTENT"	VARCHAR2(4000)		NULL,
	"SEND_DATE"	TIMESTAMP		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(4000)		NULL,
	"CHANGE_NAME"	VARCHAR2(4000)		NULL
);

COMMENT ON COLUMN "TB_CHATCONTENT"."CHATCONTENT_NO" IS '채팅내용 번호';

COMMENT ON COLUMN "TB_CHATCONTENT"."CHATROOM_NO" IS '채팅방 번호';

COMMENT ON COLUMN "TB_CHATCONTENT"."WRITER_NO" IS '작성자 번호';

COMMENT ON COLUMN "TB_CHATCONTENT"."CHAT_CONTENT" IS '채팅 내용';

COMMENT ON COLUMN "TB_CHATCONTENT"."SEND_DATE" IS '전송 시간';

COMMENT ON COLUMN "TB_CHATCONTENT"."ORIGIN_NAME" IS '원본명';

COMMENT ON COLUMN "TB_CHATCONTENT"."CHANGE_NAME" IS '수정명';

DROP TABLE "TB_CHATMEMBER";

CREATE TABLE "TB_CHATMEMBER" (
	"CHATROOM_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ENROLL_DATE"	DATE		NOT NULL,
	"NOT_READ"	NUMBER		NULL
);

COMMENT ON COLUMN "TB_CHATMEMBER"."CHATROOM_NO" IS '채팅방 번호';

COMMENT ON COLUMN "TB_CHATMEMBER"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_CHATMEMBER"."ENROLL_DATE" IS '들어온날짜';

COMMENT ON COLUMN "TB_CHATMEMBER"."NOT_READ" IS '안읽은메세지갯수';

DROP TABLE "TB_APPROVAL";

CREATE TABLE "TB_APPROVAL" (
	"APPRO_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"TLP_NO"	NUMBER		NOT NULL,
	"APPRO_TITLE"	VARCHAR2(255)		NOT NULL,
	"APPRO_CONTENT"	CLOB		NOT NULL,
	"INTER_NO"	NUMBER		NULL,
	"INTER_APPRO"	VARCHAR2(255)		NULL,
	"FINAL_NO"	NUMBER		NOT NULL,
	"FINAL_APPRO"	VARCHAR2(255)		NOT NULL,
	"CREATE_DATE"	VARCHAR2(255)	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "TB_APPROVAL"."APPRO_NO" IS '결재번호';

COMMENT ON COLUMN "TB_APPROVAL"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_APPROVAL"."TLP_NO" IS '결재서식번호';

COMMENT ON COLUMN "TB_APPROVAL"."APPRO_TITLE" IS '결재제목';

COMMENT ON COLUMN "TB_APPROVAL"."APPRO_CONTENT" IS '결재내용';

COMMENT ON COLUMN "TB_APPROVAL"."INTER_NO" IS '중간결재자  회원번호';

COMMENT ON COLUMN "TB_APPROVAL"."INTER_APPRO" IS '대기/결재/반려';

COMMENT ON COLUMN "TB_APPROVAL"."FINAL_NO" IS '최종결재자 회원번호';

COMMENT ON COLUMN "TB_APPROVAL"."FINAL_APPRO" IS '대기/결재/반려';

COMMENT ON COLUMN "TB_APPROVAL"."CREATE_DATE" IS '생성일(VARCHAR2)';

COMMENT ON COLUMN "TB_APPROVAL"."STATUS" IS 'STATUS';

DROP TABLE "TB_APP_TPL";

CREATE TABLE "TB_APP_TPL" (
	"TPL_NO"	NUMBER		NOT NULL,
	"TPL_TITLE"	VARCHAR2(255)		NOT NULL,
	"TPL_CONTENT"	CLOB		NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "TB_APP_TPL"."TPL_NO" IS '결재서식번호';

COMMENT ON COLUMN "TB_APP_TPL"."TPL_TITLE" IS '결재서식제목';

COMMENT ON COLUMN "TB_APP_TPL"."TPL_CONTENT" IS '결재서식내용';

COMMENT ON COLUMN "TB_APP_TPL"."STATUS" IS 'STATUS';

DROP TABLE "TB_APP_REF";

CREATE TABLE "TB_APP_REF" (
	"REF_NO"	NUMBER		NOT NULL,
	"APPRO_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"REF_LVL"	VARCHAR2(255)		NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "TB_APP_REF"."REF_NO" IS '참조번호';

COMMENT ON COLUMN "TB_APP_REF"."APPRO_NO" IS '결재번호';

COMMENT ON COLUMN "TB_APP_REF"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_APP_REF"."REF_LVL" IS '참조/열람';

COMMENT ON COLUMN "TB_APP_REF"."STATUS" IS 'STATUS';

DROP TABLE "TB_ADDRESSBOOK";

CREATE TABLE "TB_ADDRESSBOOK" (
	"ADD_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(50)		NULL,
	"DEPT_NAME"	VARCHAR2(50)		NULL,
	"JOB_NAME"	VARCHAR2(50)		NULL,
	"EMAIL"	VARCHAR2(100)		NULL,
	"PHONE"	VARCHAR2(20)		NULL,
	"BIZ_NAME"	VARCHAR2(50)		NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NULL,
	"GROUP_NO"	NUMBER		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "TB_ADDRESSBOOK"."ADD_NO" IS '주소록번호';

COMMENT ON COLUMN "TB_ADDRESSBOOK"."NAME" IS '직원이름';

COMMENT ON COLUMN "TB_ADDRESSBOOK"."DEPT_NAME" IS '부서명';

COMMENT ON COLUMN "TB_ADDRESSBOOK"."JOB_NAME" IS '직급명';

COMMENT ON COLUMN "TB_ADDRESSBOOK"."EMAIL" IS '이메일';

COMMENT ON COLUMN "TB_ADDRESSBOOK"."PHONE" IS '전화번호';

COMMENT ON COLUMN "TB_ADDRESSBOOK"."BIZ_NAME" IS '업체명';

COMMENT ON COLUMN "TB_ADDRESSBOOK"."STATUS" IS '상태(Y/N)';

COMMENT ON COLUMN "TB_ADDRESSBOOK"."GROUP_NO" IS '그룹번호';

COMMENT ON COLUMN "TB_ADDRESSBOOK"."MEMBER_NO" IS '등록한사원번호';

DROP TABLE "TB_ADDESSGROUP";

CREATE TABLE "TB_ADDESSGROUP" (
	"GROUP_NO"	NUMBER		NOT NULL,
	"GROUP_NAME"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"STATUS"	CAHR(1)	DEFAULT 'Y'	NULL
);

COMMENT ON COLUMN "TB_ADDESSGROUP"."GROUP_NO" IS '그룹번호';

COMMENT ON COLUMN "TB_ADDESSGROUP"."GROUP_NAME" IS '그룹이름';

COMMENT ON COLUMN "TB_ADDESSGROUP"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_ADDESSGROUP"."STATUS" IS '상태Y/N)';

DROP TABLE "TB_MAIL_FILE";

CREATE TABLE "TB_MAIL_FILE" (
	"EMF_NO"	NUMBER		NOT NULL,
	"EM_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(500)		NULL,
	"CHANGE_NAME"	VARCHAR2(500)		NULL,
	"FILE_PATH"	VARCHAR2(500)		NULL,
	"STATUS"	VARCHAR2(50)		NULL,
	"FILE_SIZE"	VARCHAR2(50)		NULL
);

COMMENT ON COLUMN "TB_MAIL_FILE"."EMF_NO" IS '파일번호';

COMMENT ON COLUMN "TB_MAIL_FILE"."EM_NO" IS '메일번호';

COMMENT ON COLUMN "TB_MAIL_FILE"."ORIGIN_NAME" IS '파일원본명';

COMMENT ON COLUMN "TB_MAIL_FILE"."CHANGE_NAME" IS '파일수정명';

COMMENT ON COLUMN "TB_MAIL_FILE"."FILE_PATH" IS '파일경로';

COMMENT ON COLUMN "TB_MAIL_FILE"."STATUS" IS '첨부파일상태';

COMMENT ON COLUMN "TB_MAIL_FILE"."FILE_SIZE" IS '파일크기';

DROP TABLE "TB_PROJECT";

CREATE TABLE "TB_PROJECT" (
	"PROJECT_NO"	NUMBER		NOT NULL,
	"OWNER_NO"	NUMBER		NOT NULL,
	"PROJECT_TITLE"	VARCHAR2(4000)		NOT NULL,
	"PROJECT_CONTENT"	VARCHAR2(4000)		NULL,
	"PUBLIC_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "TB_PROJECT"."PROJECT_NO" IS '프로젝트 번호';

COMMENT ON COLUMN "TB_PROJECT"."OWNER_NO" IS '방장 번호';

COMMENT ON COLUMN "TB_PROJECT"."PROJECT_TITLE" IS '프로젝트 이름';

COMMENT ON COLUMN "TB_PROJECT"."PROJECT_CONTENT" IS '프로젝트 설명';

COMMENT ON COLUMN "TB_PROJECT"."PUBLIC_STATUS" IS ''Y':공개, 'N':비공개';

COMMENT ON COLUMN "TB_PROJECT"."CREATE_DATE" IS '생성일';

COMMENT ON COLUMN "TB_PROJECT"."STATUS" IS '상태';

DROP TABLE "TB_PROJECTMEMBER";

CREATE TABLE "TB_PROJECTMEMBER" (
	"PROJECT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"STATUS"	NUMBER	DEFAULT 1	NOT NULL,
	"ENROLL_DATE"	DATE		NULL
);

COMMENT ON COLUMN "TB_PROJECTMEMBER"."PROJECT_NO" IS '프로젝트 번호';

COMMENT ON COLUMN "TB_PROJECTMEMBER"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_PROJECTMEMBER"."STATUS" IS '1 : 참여 / 2 : 참여 요청 / 3 : 나감';

COMMENT ON COLUMN "TB_PROJECTMEMBER"."ENROLL_DATE" IS '참여날짜';

DROP TABLE "TB_MEMBER";

CREATE TABLE "TB_MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"DEPT_NAME"	VARCHAR2(20)		NULL,
	"JOB_NAME"	VARCHAR2(10)		NOT NULL,
	"POSITION"	VARCHAR2(10)		NULL,
	"DUTY"	VARCHAR2(30)		NULL,
	"NAME"	VARCHAR2(20)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMBER_PWD"	VARCHAR2(400)		NOT NULL,
	"RRN"	VARCHAR2(20)		NOT NULL,
	"EMAIL"	VARCHAR2(60)		NOT NULL,
	"PHONE"	VARCHAR2(20)		NOT NULL,
	"ADDRESS"	VARCHAR2(60)		NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"ENROLL_DATE"	DATE		NOT NULL,
	"OUT_DATE"	DATE		NULL,
	"LEAVE_OFF"	NUMBER		NULL,
	"WORKING_HOURS"	VARCHAR2(60)		NULL,
	"PROFILE_URL"	VARCHAR2(400)		NULL
);

COMMENT ON COLUMN "TB_MEMBER"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_MEMBER"."DEPT_NAME" IS '부서명';

COMMENT ON COLUMN "TB_MEMBER"."JOB_NAME" IS '직급명';

COMMENT ON COLUMN "TB_MEMBER"."POSITION" IS '직책명';

COMMENT ON COLUMN "TB_MEMBER"."DUTY" IS '담당업무';

COMMENT ON COLUMN "TB_MEMBER"."NAME" IS '이름';

COMMENT ON COLUMN "TB_MEMBER"."MEMBER_ID" IS '아이디';

COMMENT ON COLUMN "TB_MEMBER"."MEMBER_PWD" IS '비밀번호';

COMMENT ON COLUMN "TB_MEMBER"."RRN" IS '주민등록번호';

COMMENT ON COLUMN "TB_MEMBER"."EMAIL" IS '이메일';

COMMENT ON COLUMN "TB_MEMBER"."PHONE" IS '휴대폰 번호';

COMMENT ON COLUMN "TB_MEMBER"."ADDRESS" IS '주소';

COMMENT ON COLUMN "TB_MEMBER"."STATUS" IS '재직상태표시';

COMMENT ON COLUMN "TB_MEMBER"."ENROLL_DATE" IS '입사날짜';

COMMENT ON COLUMN "TB_MEMBER"."OUT_DATE" IS '퇴사날짜';

COMMENT ON COLUMN "TB_MEMBER"."LEAVE_OFF" IS '총연차개수';

COMMENT ON COLUMN "TB_MEMBER"."WORKING_HOURS" IS '한달간 총 근무시간';

COMMENT ON COLUMN "TB_MEMBER"."PROFILE_URL" IS '수정 프로필 사진 경로';

DROP TABLE "TB_LIST";

CREATE TABLE "TB_LIST" (
	"LIST_NO"	NUMBER		NOT NULL,
	"PROJECT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"LIST_TITLE"	VARCHAR2(4000)		NOT NULL,
	"BEGIN_DATE"	VARCHAR2(100)		NOT NULL,
	"END_DATE"	VARCHAR2(100)		NOT NULL,
	"COLOR"	VARCHAR2(100)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "TB_LIST"."LIST_NO" IS '리스트 번호';

COMMENT ON COLUMN "TB_LIST"."PROJECT_NO" IS '프로젝트 번호';

COMMENT ON COLUMN "TB_LIST"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_LIST"."LIST_TITLE" IS '리스트 이름';

COMMENT ON COLUMN "TB_LIST"."BEGIN_DATE" IS '시작일';

COMMENT ON COLUMN "TB_LIST"."END_DATE" IS '종료일';

COMMENT ON COLUMN "TB_LIST"."COLOR" IS '색상';

COMMENT ON COLUMN "TB_LIST"."ENROLL_DATE" IS '등록일';

DROP TABLE "TB_TODO";

CREATE TABLE "TB_TODO" (
	"TODO_NO"	NUMBER		NOT NULL,
	"LIST_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"TODO_TITLE"	VARCHAR2(4000)		NOT NULL,
	"FINISH_STATUS"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "TB_TODO"."TODO_NO" IS '할일 번호';

COMMENT ON COLUMN "TB_TODO"."LIST_NO" IS '리스트 번호';

COMMENT ON COLUMN "TB_TODO"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_TODO"."TODO_TITLE" IS '할일제목';

COMMENT ON COLUMN "TB_TODO"."FINISH_STATUS" IS '완료여부';

COMMENT ON COLUMN "TB_TODO"."ENROLL_DATE" IS '등록일';

DROP TABLE "TB_LISTCHAT";

CREATE TABLE "TB_LISTCHAT" (
	"CHAT_NO"	NUMBER		NOT NULL,
	"LIST_NO"	NUMBER		NOT NULL,
	"WRITER_NO"	NUMBER		NOT NULL,
	"CHAT_CONTENT"	VARCHAR2(4000)		NULL,
	"ORIGIN_NAME"	VARCHAR2(4000)		NULL,
	"CHANGE_NAME"	VARCHAR2(4000)		NULL,
	"SEND_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "TB_LISTCHAT"."CHAT_NO" IS '채팅 번호';

COMMENT ON COLUMN "TB_LISTCHAT"."LIST_NO" IS '리스트 번호';

COMMENT ON COLUMN "TB_LISTCHAT"."WRITER_NO" IS '작성자 번호';

COMMENT ON COLUMN "TB_LISTCHAT"."CHAT_CONTENT" IS '채팅 내용';

COMMENT ON COLUMN "TB_LISTCHAT"."ORIGIN_NAME" IS '원본명';

COMMENT ON COLUMN "TB_LISTCHAT"."CHANGE_NAME" IS '수정명';

COMMENT ON COLUMN "TB_LISTCHAT"."SEND_DATE" IS '전송 시간';

DROP TABLE "TB_PJSCHEDULE";

CREATE TABLE "TB_PJSCHEDULE" (
	"SCHEDULE_NO"	NUMBER		NOT NULL,
	"PROJECT_NO"	NUMBER		NOT NULL,
	"SCHEDULE_NAME"	VARCHAR2(4000)		NOT NULL,
	"BEGIN_DATE"	VARCHAR2(100)		NOT NULL,
	"END_DATE"	VARCHAR2(100)		NOT NULL,
	"SCHEDULE_WRITER"	NUMBER		NOT NULL,
	"COLOR"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "TB_PJSCHEDULE"."SCHEDULE_NO" IS '일정 번호';

COMMENT ON COLUMN "TB_PJSCHEDULE"."PROJECT_NO" IS '프로젝트 번호';

COMMENT ON COLUMN "TB_PJSCHEDULE"."SCHEDULE_NAME" IS '일정 이름';

COMMENT ON COLUMN "TB_PJSCHEDULE"."BEGIN_DATE" IS '시작일';

COMMENT ON COLUMN "TB_PJSCHEDULE"."END_DATE" IS '종료일';

COMMENT ON COLUMN "TB_PJSCHEDULE"."SCHEDULE_WRITER" IS '작성자';

COMMENT ON COLUMN "TB_PJSCHEDULE"."COLOR" IS '색상';

DROP TABLE "TB_LIKE";

CREATE TABLE "TB_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PROJECT_NO"	NUMBER		NOT NULL,
	"LIKE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "TB_LIKE"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_LIKE"."PROJECT_NO" IS '프로젝트 번호';

COMMENT ON COLUMN "TB_LIKE"."LIKE_DATE" IS '즐겨찾기한날짜';

DROP TABLE "TB_DAYOFF";

CREATE TABLE "TB_DAYOFF" (
	"DAYOFF_NO"	VARCHAR(255)		NOT NULL,
	"NAME"	VARCHAR2(20)		NOT NULL,
	"APPLY_DATE"	VARCHAR2(60)		NOT NULL,
	"CANCEL_DATE"	VARCHAR2(60)	DEFAULT 'N'	NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"APPLICANT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "TB_DAYOFF"."DAYOFF_NO" IS 'SEQ';

COMMENT ON COLUMN "TB_DAYOFF"."NAME" IS '신청자이름';

COMMENT ON COLUMN "TB_DAYOFF"."APPLY_DATE" IS '연차 신청한 날짜';

COMMENT ON COLUMN "TB_DAYOFF"."CANCEL_DATE" IS '연차 취소한 날짜';

COMMENT ON COLUMN "TB_DAYOFF"."STATUS" IS '연차 중인지  아닌지 상태';

COMMENT ON COLUMN "TB_DAYOFF"."APPLICANT_NO" IS '사원번호';

DROP TABLE "TB_COMMUTE";

CREATE TABLE "TB_COMMUTE" (
	"COMMUTE_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(20)		NOT NULL,
	"COMMUTE_IN"	VARCHAR2(60)		NOT NULL,
	"COMMUTE_OUT"	VARCHAR2(60)		NOT NULL,
	"COMMUTE_DATE"	VARCHAR2(60)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"Field"	VARCHAR2(60)	DEFAULT NULL	NULL
);

COMMENT ON COLUMN "TB_COMMUTE"."COMMUTE_NO" IS 'SEQ';

COMMENT ON COLUMN "TB_COMMUTE"."NAME" IS '이름';

COMMENT ON COLUMN "TB_COMMUTE"."COMMUTE_IN" IS '출근시간';

COMMENT ON COLUMN "TB_COMMUTE"."COMMUTE_OUT" IS '퇴근시간';

COMMENT ON COLUMN "TB_COMMUTE"."COMMUTE_DATE" IS '출근한 날짜';

COMMENT ON COLUMN "TB_COMMUTE"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_COMMUTE"."Field" IS '지각/조퇴/정상근무/연차/결근';

DROP TABLE "TB_BOARD";

CREATE TABLE "TB_BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	CLOB		NOT NULL,
	"BOARD_WRITER"	VARCHAR2(30)		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NULL,
	"CHANGE_NAME"	VARCHAR2(100)		NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"COUNT"	NUMBER	DEFAULT 0	NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	"CATEGORY"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "TB_BOARD"."BOARD_NO" IS '게시글번호';

COMMENT ON COLUMN "TB_BOARD"."BOARD_TITLE" IS '게시글제목';

COMMENT ON COLUMN "TB_BOARD"."BOARD_CONTENT" IS '게시글내용';

COMMENT ON COLUMN "TB_BOARD"."BOARD_WRITER" IS '게시글작성자';

COMMENT ON COLUMN "TB_BOARD"."ORIGIN_NAME" IS '첨부파일원본명';

COMMENT ON COLUMN "TB_BOARD"."CHANGE_NAME" IS '첨부파일변경';

COMMENT ON COLUMN "TB_BOARD"."CREATE_DATE" IS '작성날짜';

COMMENT ON COLUMN "TB_BOARD"."COUNT" IS '게시글조회수';

COMMENT ON COLUMN "TB_BOARD"."STATUS" IS '상태';

COMMENT ON COLUMN "TB_BOARD"."CATEGORY" IS '1/2/3/4/자유게시판(5)/공지사항(6)';

DROP TABLE "TB_REPORT";

CREATE TABLE "TB_REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"POST_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"REPORT_CONTENT"	VARCHAR2(100)		NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'N'	NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "TB_REPORT"."REPORT_NO" IS '신고번호';

COMMENT ON COLUMN "TB_REPORT"."POST_NO" IS '참조게시글번호';

COMMENT ON COLUMN "TB_REPORT"."MEMBER_NO" IS '신고자번호';

COMMENT ON COLUMN "TB_REPORT"."REPORT_CONTENT" IS '신고사유';

COMMENT ON COLUMN "TB_REPORT"."STATUS" IS '처리상태';

COMMENT ON COLUMN "TB_REPORT"."REPORT_DATE" IS '신고날짜';

DROP TABLE "TB_REPLY";

CREATE TABLE "TB_REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"POST_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(400 BYTE)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	VARCHAR2(1 BYTE)	DEFAULT 'Y'	NULL
);

COMMENT ON COLUMN "TB_REPLY"."REPLY_NO" IS '댓글번호';

COMMENT ON COLUMN "TB_REPLY"."POST_NO" IS '참조게시글번호';

COMMENT ON COLUMN "TB_REPLY"."MEMBER_NO" IS '작성자번호';

COMMENT ON COLUMN "TB_REPLY"."REPLY_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "TB_REPLY"."CREATE_DATE" IS '댓글작성일';

COMMENT ON COLUMN "TB_REPLY"."STATUS" IS '상태';

DROP TABLE "TB_M_SCHEDULE";

CREATE TABLE "TB_M_SCHEDULE" (
	"SCHEDULE_NO"	NUMBER		NOT NULL,
	"START_DATE"	VARCHAR2(50)		NOT NULL,
	"END_DATE"	VARCHAR2(50)		NOT NULL,
	"START_TIME"	VARCHAR2(50)		NULL,
	"END_TIME"	VARCHAR2(50)		NULL,
	"SC_TITLE"	VARCHAR2(300)		NOT NULL,
	"SC_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"WRITE_DATE"	VARCHAR2(50)		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"CALENDAR_NO"	NUMBER		NULL,
	"ALLDAY"	VARCHAR2(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "TB_M_SCHEDULE"."STATUS" IS '존재(Y) / 삭제(N)';

COMMENT ON COLUMN "TB_M_SCHEDULE"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_M_SCHEDULE"."ALLDAY" IS '종일(Y) / 시간선택가능(N)';

DROP TABLE "TB_CATEGORY";

CREATE TABLE "TB_CATEGORY" (
	"CALENDAR_NO"	NUMBER		NULL,
	"MY_CALENDAR"	VARCHAR2(1000)		NOT NULL,
	"SC_COLOR"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

DROP TABLE "TB_RESERVATION";

CREATE TABLE "TB_RESERVATION" (
	"RES_NO"	NUMBER		NOT NULL,
	"ROOM_TYPE"	VARCHAR2(20)		NOT NULL,
	"START_DATE"	VARCHAR2(50)		NOT NULL,
	"END_DATE"	VARCHAR2(50)		NOT NULL,
	"START_TIME"	VARCHAR2(50)		NULL,
	"END_TIME"	VARCHAR2(50)		NULL,
	"PEOPLE"	VARCHAR2(10)	DEFAULT 1	NOT NULL,
	"USAGE"	VARCHAR2(1000)		NOT NULL,
	"APPLY_DATE"	VARCHAR2(50)	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ALLDAY"	VARCHAR2(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "TB_RESERVATION"."ROOM_TYPE" IS 'M1 / M2 / M3';

COMMENT ON COLUMN "TB_RESERVATION"."MEMBER_NO" IS '사원번호';

COMMENT ON COLUMN "TB_RESERVATION"."ALLDAY" IS '종일(Y) / 시간선택가능(N)';

DROP TABLE "TB_ATTENDEE";

CREATE TABLE "TB_ATTENDEE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"SCHEDULE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "TB_ATTENDEE"."MEMBER_NO" IS '사원번호';

DROP TABLE "TB_MAIL";

CREATE TABLE "TB_MAIL" (
	"EM_NO"	NUMBER		NOT NULL,
	"EM_TITLE"	VARCHAR2(2000)		NULL,
	"EM_CONTENT"	CLOB		NULL,
	"MEM_NAME"	VARCHAR2(100)		NULL,
	"SENDER"	VARCHAR2(100)		NULL,
	"RECEIVER"	VARCHAR2(2000)		NULL,
	"REF_EMAIL"	VARCHAR2(2000)		NULL,
	"SEND_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"TEMP_STOCK"	VARCHAR2(50)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "TB_MAIL"."EM_NO" IS '메일번호';

COMMENT ON COLUMN "TB_MAIL"."EM_TITLE" IS '메일제목';

COMMENT ON COLUMN "TB_MAIL"."EM_CONTENT" IS '메일내용';

COMMENT ON COLUMN "TB_MAIL"."MEM_NAME" IS '보낸사람이름';

COMMENT ON COLUMN "TB_MAIL"."SENDER" IS '보낸사람이메일';

COMMENT ON COLUMN "TB_MAIL"."RECEIVER" IS '받는사람(이메일,이메일,이메일)';

COMMENT ON COLUMN "TB_MAIL"."REF_EMAIL" IS '참조자(이메일,이메일,이메일)';

COMMENT ON COLUMN "TB_MAIL"."SEND_DATE" IS '보낸날짜';

COMMENT ON COLUMN "TB_MAIL"."TEMP_STOCK" IS '보관여부(Y/N)';

DROP TABLE "TB_MAIL_STATUS";

CREATE TABLE "TB_MAIL_STATUS" (
	"EM_NO"	NUMBER		NOT NULL,
	"EM_TYPE"	VARCHAR2(100)		NULL,
	"RECEIVER_NAME"	VARCHAR2(50)		NULL,
	"RECEIVER"	VARCHAR2(100)		NULL,
	"READ"	CHAR(1)	DEFAULT 'N'	NULL,
	"READ_TIME"	VARCHAR2(100)		NULL,
	"IMPORTANT"	CHAR(1)	DEFAULT 'N'	NULL,
	"TRASH"	CHAR(1)	DEFAULT 'N'	NULL,
	"SPAM"	CHAR(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "TB_MAIL_STATUS"."EM_NO" IS '메일번호';

COMMENT ON COLUMN "TB_MAIL_STATUS"."EM_TYPE" IS '보낸메일/받은메일/참조된메일';

COMMENT ON COLUMN "TB_MAIL_STATUS"."RECEIVER_NAME" IS '수신자이름';

COMMENT ON COLUMN "TB_MAIL_STATUS"."RECEIVER" IS '보낸메일일 경우 NULL, 받은메일 또는 참조된메일일 경우 수신자이메일 1개';

COMMENT ON COLUMN "TB_MAIL_STATUS"."READ" IS 'Y/N';

COMMENT ON COLUMN "TB_MAIL_STATUS"."READ_TIME" IS '읽은날짜시간';

COMMENT ON COLUMN "TB_MAIL_STATUS"."IMPORTANT" IS 'Y/N';

COMMENT ON COLUMN "TB_MAIL_STATUS"."TRASH" IS 'Y/N';

COMMENT ON COLUMN "TB_MAIL_STATUS"."SPAM" IS 'Y/N';

ALTER TABLE "TB_CHATROOM" ADD CONSTRAINT "PK_TB_CHATROOM" PRIMARY KEY (
	"CHATROOM_NO"
);

ALTER TABLE "TB_CHATCONTENT" ADD CONSTRAINT "PK_TB_CHATCONTENT" PRIMARY KEY (
	"CHATCONTENT_NO"
);

ALTER TABLE "TB_CHATMEMBER" ADD CONSTRAINT "PK_TB_CHATMEMBER" PRIMARY KEY (
	"CHATROOM_NO",
	"MEMBER_NO"
);

ALTER TABLE "TB_APPROVAL" ADD CONSTRAINT "PK_TB_APPROVAL" PRIMARY KEY (
	"APPRO_NO"
);

ALTER TABLE "TB_APP_TPL" ADD CONSTRAINT "PK_TB_APP_TPL" PRIMARY KEY (
	"TPL_NO"
);

ALTER TABLE "TB_APP_REF" ADD CONSTRAINT "PK_TB_APP_REF" PRIMARY KEY (
	"REF_NO"
);

ALTER TABLE "TB_ADDRESSBOOK" ADD CONSTRAINT "PK_TB_ADDRESSBOOK" PRIMARY KEY (
	"ADD_NO"
);

ALTER TABLE "TB_ADDESSGROUP" ADD CONSTRAINT "PK_TB_ADDESSGROUP" PRIMARY KEY (
	"GROUP_NO"
);

ALTER TABLE "TB_MAIL_FILE" ADD CONSTRAINT "PK_TB_MAIL_FILE" PRIMARY KEY (
	"EMF_NO"
);

ALTER TABLE "TB_PROJECT" ADD CONSTRAINT "PK_TB_PROJECT" PRIMARY KEY (
	"PROJECT_NO"
);

ALTER TABLE "TB_PROJECTMEMBER" ADD CONSTRAINT "PK_TB_PROJECTMEMBER" PRIMARY KEY (
	"PROJECT_NO",
	"MEMBER_NO"
);

ALTER TABLE "TB_MEMBER" ADD CONSTRAINT "PK_TB_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "TB_LIST" ADD CONSTRAINT "PK_TB_LIST" PRIMARY KEY (
	"LIST_NO"
);

ALTER TABLE "TB_TODO" ADD CONSTRAINT "PK_TB_TODO" PRIMARY KEY (
	"TODO_NO"
);

ALTER TABLE "TB_LISTCHAT" ADD CONSTRAINT "PK_TB_LISTCHAT" PRIMARY KEY (
	"CHAT_NO"
);

ALTER TABLE "TB_PJSCHEDULE" ADD CONSTRAINT "PK_TB_PJSCHEDULE" PRIMARY KEY (
	"SCHEDULE_NO"
);

ALTER TABLE "TB_LIKE" ADD CONSTRAINT "PK_TB_LIKE" PRIMARY KEY (
	"MEMBER_NO",
	"PROJECT_NO"
);

ALTER TABLE "TB_DAYOFF" ADD CONSTRAINT "PK_TB_DAYOFF" PRIMARY KEY (
	"DAYOFF_NO"
);

ALTER TABLE "TB_COMMUTE" ADD CONSTRAINT "PK_TB_COMMUTE" PRIMARY KEY (
	"COMMUTE_NO"
);

ALTER TABLE "TB_BOARD" ADD CONSTRAINT "PK_TB_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "PK_TB_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "TB_REPLY" ADD CONSTRAINT "PK_TB_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "TB_M_SCHEDULE" ADD CONSTRAINT "PK_TB_M_SCHEDULE" PRIMARY KEY (
	"SCHEDULE_NO"
);

ALTER TABLE "TB_CATEGORY" ADD CONSTRAINT "PK_TB_CATEGORY" PRIMARY KEY (
	"CALENDAR_NO"
);

ALTER TABLE "TB_RESERVATION" ADD CONSTRAINT "PK_TB_RESERVATION" PRIMARY KEY (
	"RES_NO"
);

ALTER TABLE "TB_ATTENDEE" ADD CONSTRAINT "PK_TB_ATTENDEE" PRIMARY KEY (
	"MEMBER_NO",
	"SCHEDULE_NO"
);

ALTER TABLE "TB_MAIL" ADD CONSTRAINT "PK_TB_MAIL" PRIMARY KEY (
	"EM_NO"
);

ALTER TABLE "TB_CHATCONTENT" ADD CONSTRAINT "FK_TB_CHATROOM_TO_TB_CHATCONTENT_1" FOREIGN KEY (
	"CHATROOM_NO"
)
REFERENCES "TB_CHATROOM" (
	"CHATROOM_NO"
);

ALTER TABLE "TB_CHATCONTENT" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_CHATCONTENT_1" FOREIGN KEY (
	"WRITER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_CHATMEMBER" ADD CONSTRAINT "FK_TB_CHATROOM_TO_TB_CHATMEMBER_1" FOREIGN KEY (
	"CHATROOM_NO"
)
REFERENCES "TB_CHATROOM" (
	"CHATROOM_NO"
);

ALTER TABLE "TB_CHATMEMBER" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_CHATMEMBER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_APPROVAL" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_APPROVAL_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_APPROVAL" ADD CONSTRAINT "FK_TB_APP_TPL_TO_TB_APPROVAL_1" FOREIGN KEY (
	"TLP_NO"
)
REFERENCES "TB_APP_TPL" (
	"TPL_NO"
);

ALTER TABLE "TB_APP_REF" ADD CONSTRAINT "FK_TB_APPROVAL_TO_TB_APP_REF_1" FOREIGN KEY (
	"APPRO_NO"
)
REFERENCES "TB_APPROVAL" (
	"APPRO_NO"
);

ALTER TABLE "TB_APP_REF" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_APP_REF_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_ADDRESSBOOK" ADD CONSTRAINT "FK_TB_ADDESSGROUP_TO_TB_ADDRESSBOOK_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "TB_ADDESSGROUP" (
	"GROUP_NO"
);

ALTER TABLE "TB_ADDRESSBOOK" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_ADDRESSBOOK_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_ADDESSGROUP" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_ADDESSGROUP_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_MAIL_FILE" ADD CONSTRAINT "FK_TB_MAIL_TO_TB_MAIL_FILE_1" FOREIGN KEY (
	"EM_NO"
)
REFERENCES "TB_MAIL" (
	"EM_NO"
);

ALTER TABLE "TB_PROJECT" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_PROJECT_1" FOREIGN KEY (
	"OWNER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_PROJECTMEMBER" ADD CONSTRAINT "FK_TB_PROJECT_TO_TB_PROJECTMEMBER_1" FOREIGN KEY (
	"PROJECT_NO"
)
REFERENCES "TB_PROJECT" (
	"PROJECT_NO"
);

ALTER TABLE "TB_PROJECTMEMBER" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_PROJECTMEMBER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_LIST" ADD CONSTRAINT "FK_TB_PROJECT_TO_TB_LIST_1" FOREIGN KEY (
	"PROJECT_NO"
)
REFERENCES "TB_PROJECT" (
	"PROJECT_NO"
);

ALTER TABLE "TB_LIST" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_LIST_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_TODO" ADD CONSTRAINT "FK_TB_LIST_TO_TB_TODO_1" FOREIGN KEY (
	"LIST_NO"
)
REFERENCES "TB_LIST" (
	"LIST_NO"
);

ALTER TABLE "TB_TODO" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_TODO_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_LISTCHAT" ADD CONSTRAINT "FK_TB_LIST_TO_TB_LISTCHAT_1" FOREIGN KEY (
	"LIST_NO"
)
REFERENCES "TB_LIST" (
	"LIST_NO"
);

ALTER TABLE "TB_LISTCHAT" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_LISTCHAT_1" FOREIGN KEY (
	"WRITER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_PJSCHEDULE" ADD CONSTRAINT "FK_TB_PROJECT_TO_TB_PJSCHEDULE_1" FOREIGN KEY (
	"PROJECT_NO"
)
REFERENCES "TB_PROJECT" (
	"PROJECT_NO"
);

ALTER TABLE "TB_LIKE" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_LIKE" ADD CONSTRAINT "FK_TB_PROJECT_TO_TB_LIKE_1" FOREIGN KEY (
	"PROJECT_NO"
)
REFERENCES "TB_PROJECT" (
	"PROJECT_NO"
);

ALTER TABLE "TB_DAYOFF" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_DAYOFF_1" FOREIGN KEY (
	"APPLICANT_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_COMMUTE" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_COMMUTE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_BOARD" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_BOARD_1" FOREIGN KEY (
	"BOARD_WRITER"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "FK_TB_BOARD_TO_TB_REPORT_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "TB_BOARD" (
	"BOARD_NO"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_REPORT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_REPLY" ADD CONSTRAINT "FK_TB_BOARD_TO_TB_REPLY_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "TB_BOARD" (
	"BOARD_NO"
);

ALTER TABLE "TB_REPLY" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_REPLY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_M_SCHEDULE" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_M_SCHEDULE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_M_SCHEDULE" ADD CONSTRAINT "FK_TB_CATEGORY_TO_TB_M_SCHEDULE_1" FOREIGN KEY (
	"CALENDAR_NO"
)
REFERENCES "TB_CATEGORY" (
	"CALENDAR_NO"
);

ALTER TABLE "TB_CATEGORY" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_CATEGORY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_RESERVATION" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_RESERVATION_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_ATTENDEE" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_ATTENDEE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "TB_ATTENDEE" ADD CONSTRAINT "FK_TB_M_SCHEDULE_TO_TB_ATTENDEE_1" FOREIGN KEY (
	"SCHEDULE_NO"
)
REFERENCES "TB_M_SCHEDULE" (
	"SCHEDULE_NO"
);

ALTER TABLE "TB_MAIL_STATUS" ADD CONSTRAINT "FK_TB_MAIL_TO_TB_MAIL_STATUS_1" FOREIGN KEY (
	"EM_NO"
)
REFERENCES "TB_MAIL" (
	"EM_NO"
);

ALTER TABLE TB_STYLE_IMG
   ADD CHECK (STATUS IN ('Y', 'N'));

